[package]
name = "dust-mail-desktop"
version = "0.1.4"
description = "A simple material mail client"
authors = ["Guus van Meerveld"]
license = "MIT"
repository = "https://github.com/Guusvanmeerveld/Dust-Mail"
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.3", features = ["isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3", features = ["devtools", "isolation", "shell-open", "system-tray", "window-close", "window-create"] }
dust-mail = { git = "https://github.com/Dust-Mail/core", rev = "df70f898c961c5f441f9873d6ec24568603d937c" }
base64 = "0.21"
directories = "4.0"
futures = "0.3"
dashmap = "5.4.0"
keyring = "2.0.2"
data-encoding = "2.3.3"
ring = "0.16.20"
whoami = "1.4.0"
env_logger = "0.10.0"
log = "0.4.19"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "dev" }
